// Mocks generated by Mockito 5.4.4 from annotations
// in my_flutter_app/test/features/preferences/domain/usecases/add_preference_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:fpdart/fpdart.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:my_flutter_app/core/error/failure.dart' as _i5;
import 'package:my_flutter_app/features/preferences/domain/entities/preference.dart'
    as _i6;
import 'package:my_flutter_app/features/preferences/domain/repositories/i_preference_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [IPreferenceRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIPreferenceRepository extends _i1.Mock
    implements _i2.IPreferenceRepository {
  MockIPreferenceRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.Failure, List<_i6.Preference>>> getPreferences() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPreferences,
          [],
        ),
        returnValue:
            _i3.Future<_i4.Either<_i5.Failure, List<_i6.Preference>>>.value(
                _i7.dummyValue<_i4.Either<_i5.Failure, List<_i6.Preference>>>(
          this,
          Invocation.method(
            #getPreferences,
            [],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.Failure, List<_i6.Preference>>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> addPreference(
          _i6.Preference? preference) =>
      (super.noSuchMethod(
        Invocation.method(
          #addPreference,
          [preference],
        ),
        returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
            _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
          this,
          Invocation.method(
            #addPreference,
            [preference],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.Failure, void>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> deletePreference(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #deletePreference,
          [id],
        ),
        returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
            _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
          this,
          Invocation.method(
            #deletePreference,
            [id],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.Failure, void>>);
}
